# docker-compose -f docker-compose.dev.yml up --build
version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      JWT_SECRET: ssshhhhh,secret!!!
      MYSQL_HOST: db
      MYSQL_DATABASE: artic-api
      MYSQL_USER: artic-api-user
      MYSQL_PASSWORD: pwrd
      
    volumes:
      - .:/app # mounts container app on local code
      - /app/node_modules

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: artic-api
      MYSQL_USER: artic-api-user
      MYSQL_PASSWORD: pwrd
      MYSQL_ROOT_PASSWORD: pwrd
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # initialized db
    
volumes:
  db_data: {}
